
server:
  port: 8080

spring:
  application:
    name: comptes
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:comptes
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
rsa:
  public-key: classpath:Keys/publicKey.pem